group:
  - files: 
    - requirements.txt
    repos: |
      ObsidianPublisher/obsidian-mkdocs-publisher-template
      sandboxingRepo/obsidian-sandbox
  - files:
    - source: overrides/
      dest: overrides/
      exclude: |
        404.html
        partials/comments.html
    - docs/assets/css/template
    - .github/workflows/create_index.yml
    - .github/workflows/mkdocs_build.yml
    - .github/workflows/update_requirements.yml
    - docs/assets/js
    repos: |
      ObsidianPublisher/obsidian-mkdocs-publisher-template
      ObsidianPublisher/obsidian-mkdocs-publisher-docs
      sandboxingRepo/obsidian-sandbox
  - files:
    - source: docs/assets/js/wiki_hover.js
      dest: wiki_hover.js
    repos: |
      ObsidianPublisher/tooltips-internal-link
  - files:
    - source: docs/Lagendia/Lagendia — Personnages data.md
      dest: docs/Personnages/PJ.md
    - source: "docs/Lagendia/Sanktae/index.md"
      dest: "docs/Espèces/Races intelligentes/Sanktae.md"
    repos: |
       Lagendia-Roleplay/wiki
       
