group:
  - files:
    - source: overrides/
      dest: overrides/
    - requirements.txt
    repos: |
      obsidianMkdocs/obsidian-mkdocs-publisher-template
      obsidianMkdocs/obsidian_mkdocs_publisher_docs
      sandboxingRepo/obsidian-sandbox
