group:
  repos: |
    obsidianMkdocs/obsidian-mkdocs-publisher-template
    obsidianMkdocs/obsidian_mkdocs_publisher_docs
  files:
    - source: overrides/
      dest: overrides/
    - source: .github/workflows/
      dest: .github/workflows/
