group:
  - files:
    - source: overrides/
      dest: overrides/
      exclude: |
        404.html
        partials/comments.html
    - docs/assets/css/template
    - .github/workflows/create_index.yml
    - docs/assets/js
    - find_unused_media.py
    - docs/tags.md
    - .github/workflows/update_req_clean_medias.yml
    - .github/workflows/deploy.yml
    repos: |
      ObsidianPublisher/follow_template
      ObsidianPublisher/obsidian-mkdocs-publisher-docs
      sandboxingRepo/obsidian-sandbox
  - files:
    - source: docs/assets/js/wiki_hover.js
      dest: wiki_hover.js
    repos: |
      ObsidianPublisher/tooltips-internal-link
