group:
  - files: 
    - requirements.txt
    repos: |
      obsidianMkdocs/obsidian-mkdocs-publisher-template
      sandboxingRepo/obsidian-sandbox
  - files:
    - source: overrides/
      dest: overrides/
      exclude: |
        404.html
        partials/comments.html
    - docs/assets/css/template
    - .github/workflows/create_index.yml
    - .github/workflows/mkdocs_build.yml
    - .github/workflows/update_requirements.yml
    repos: |
      obsidianMkdocs/obsidian-mkdocs-publisher-template
      obsidianMkdocs/obsidian_mkdocs_publisher_docs
      sandboxingRepo/obsidian-sandbox
