group:
  repos: |
    obsidianMkdocs/obsidian-mkdocs-publisher-template
    obsidianMkdocs/obsidian_mkdocs_publisher_docs
  files:
    - source: overrides/
      dest: overrides/
    - .github/workflows/ci.yml
    - .github/workflows/mkdocs_build.yml
    - .github/workflows/manual_run.yml
    - .github/workflows/uupdate_requirements.yml
