group:
  - files:
    - source: overrides/
      dest: overrides/
      exclude: |
        404.html
        partials/comments.html
    - find_unused_media.py
    - docs/tags.md
    repos: |
      ObsidianPublisher/sync_template
      ObsidianPublisher/docs
      sandboxingRepo/obsidian-sandbox

