group:
  - files:
    - source: overrides/
      dest: overrides/
      exclude: |
        404.html
        partials/comments.html
    - .github/workflows/create_index.yml
    - find_unused_media.py
    - docs/assets/template/
    - docs/tags.md
    - .github/workflows/update_req_clean_medias.yml
    - source: .github/workflows/deploy.yml
      dest: .github/workflows/advanced_deploy.yml
    repos: |
      ObsidianPublisher/follow_template
      ObsidianPublisher/obsidian-mkdocs-publisher-docs
      sandboxingRepo/obsidian-sandbox

