name: Publisher11
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - libsqlite
  - libzlib
  - openssl
  - pip
  - python
  - setuptools
  - tk
  - tzdata
  - ucrt
  - vc
  - vs2015_runtime
  - wheel
  - xz
  - pip:
    - asttokens
    - babel
    - backcall
    - beautifulsoup4
    - bleach
    - bracex
    - cairocffi
    - cairosvg
    - certifi
    - cffi
    - charset-normalizer
    - click
    - click-log
    - colorama
    - csscompressor
    - cssselect2
    - decorator
    - defusedxml
    - docutils
    - dotty-dict
    - editorconfig
    - executing
    - ghp-import
    - gitdb
    - gitpython
    - html2text
    - htmlmin
    - idna
    - imgkit
    - importlib-metadata
    - invoke
    - ipython
    - jaraco-classes
    - jedi
    - jinja2
    - jsbeautifier
    - jsmin
    - jsonpickle
    - keyring
    - lxml
    - markdown
    - markupsafe
    - matplotlib-inline
    - mdx-breakless-lists
    - mdx-wikilink-plus
    - mergedeep
    - mkdocs
    - mkdocs-awesome-pages-plugin
    - mkdocs-callouts
    - mkdocs-custom-fences
    - mkdocs-custom-tags-attributes
    - mkdocs-embed-file-plugins
    - mkdocs-encryptcontent-plugin
    - mkdocs-ezlinked-plugin
    - mkdocs-git-revision-date-localized-plugin
    - mkdocs-glightbox
    - mkdocs-material
    - mkdocs-material-extensions
    - mkdocs-mermaid2-plugin
    - mkdocs-meta-descriptions-plugin
    - mkdocs-minify-plugin
    - mkdocs-preview-links-plugin
    - mkdocs-simple-hooks
    - mkdocs-static-i18n
    - more-itertools
    - natsort
    - networkx
    - numpy
    - obsidiantools
    - packaging
    - pandas
    - parso
    - pickleshare
    - pillow
    - pkginfo
    - prompt-toolkit
    - pur
    - pure-eval
    - pycparser
    - pycryptodome
    - pygments
    - pygtrie
    - pymdown-extensions
    - pyparsing
    - python-dateutil
    - python-frontmatter
    - python-gitlab
    - python-semantic-release
    - pytz
    - pyvis
    - pywin32-ctypes
    - pyyaml
    - pyyaml-env-tag
    - readme-renderer
    - regex
    - requests
    - requests-toolbelt
    - rfc3986
    - semver
    - six
    - smmap
    - soupsieve
    - stack-data
    - tinycss2
    - tomlkit
    - tqdm
    - traitlets
    - twine
    - urllib3
    - watchdog
    - wcmatch
    - wcwidth
    - webencodings
    - zipp


#bash conda.exe env export | cut -f -1 -d "=" | grep -v "prefix" > environment.yml