[build]
  command = "npm install -D netlify-plugin-cache && mkdocs build"
  publish = "site"
[template]
  incoming-hooks = ["Contentful"]
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [".cache"]
