name: create index

on: 
  workflow_dispatch:
    inputs:
      category_name:
        type: string
        required: true
        description: "The new folder name"
      path:
        type: string
        required: false
        description: "The path of the new folder. Ex: category/subcategory"
      description: 
        type: string
        required: false
        description: "The description of the category."
      toc_hide:
        type: boolean
        required: false
        description: "Hide the toc in the index file."
      nav_hide:
        type: boolean
        required: false
        description: "Hide the navigation menu in the index file."
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: echo variable
        run: |
          echo "Category name : ${{ inputs.category_name }}"
          echo "Parent path : ${{ inputs.path }}"
          echo "Description : ${{ inputs.description }}"
          echo "Hide toc : ${{ inputs.toc_hide }}"
          echo "Hide nav : ${{ inputs.nav_hide }}"
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install requirements
        run: pip install pyyaml
      - name: Arguments
        run: |
          toc_hide=''
          nav_hide=''
          description=''
          parent=''
          if [[ ${{inputs.toc_hide}} -eq true ]]
          then
            toc_hide='--toc'
          fi
          if [[ ${{inputs.nav_hide}} -eq true ]]
          then
            nav_hide='--nav'
          fi
          if [[ ${{github.events.inputs.description}} -ne '' ]]
          then
            description='--description ${{github.events.inputs.description}}'
          fi
          if [[ ${{ github.events.path }} -ne '']]
          then
            parent='--parent ${{github.events.path}}'
          fi
          echo "::set-env name=toc_hide::$toc_hide"
          echo "::set-env name=nav_hide::$nav_hide"
          echo "::set-env name=description::$description"
          echo "::set-env name=parent::$parent"
      - name: get args
        run: |
          echo $toc_hide
          





