name: create index

on: 
  workflow_dispatch:
    inputs:
      category_name:
        type: string
        required: true
        description: "The new folder name"
      path:
        type: string
        required: false
        description: "The path of the new folder. Ex: category/subcategory"
      description: 
        type: string
        required: false
        description: "The description of the category."
      toc_hide:
        type: boolean
        required: false
        description: "Hide the toc in the index file."
      nav_hide:
        type: boolean
        required: false
        description: "Hide the navigation menu in the index file."
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: echo variable
        run: |
          echo "Category name : ${{ inputs.category_name }}"
          echo "Parent path : ${{ inputs.path }}"
          echo "Description : ${{ inputs.description }}"
          echo "Hide toc : ${{ inputs.toc_hide }}"
          echo "Hide nav : ${{ inputs.nav_hide }}"

