name: create index

on: 
  workflow_dispatch:
    inputs:
      category_name:
        type: string
        required: true
        description: "The new folder name"
      path:
        type: string
        required: false
        description: "The path of the new folder. Ex: category/subcategory"
      description: 
        type: string
        required: false
        description: "The description of the category."
      toc_hide:
        type: boolean
        required: false
        description: "Hide the toc in the index file."
      nav_hide:
        type: boolean
        required: false
        description: "Hide the navigation menu in the index file."
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: echo variable
        run: |
          echo 📫 Commands arguments
          echo "Category name : ${{ inputs.category_name }}"
          echo "Parent path : ${{ inputs.path }}"
          echo "Description : ${{ inputs.description }}"
          echo "Hide toc : ${{ inputs.toc_hide }}"
          echo "Hide nav : ${{ inputs.nav_hide }}"
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install requirements
        run: pip install pyyaml
      - name: Gettings arguments
        id: args
        run: |
          echo 🔁 gettings arguments
          toc_hide=''
          nav_hide=''
          description=''
          parent=''
          desc="${{ github.events.inputs.description }}"
          desc_len=${#desc}
          path="${{ github.events.inputs.path }}"
          path_len=${#path}
          if [[ ${{inputs.toc_hide}} -eq true ]]
          then
            toc_hide='--toc'
          fi
          if [[ ${{inputs.nav_hide}} -eq true ]]
          then
            nav_hide='--nav'
          fi
          if [[ $desc_len -ge 1 ]]
          then
            description='--description "${{github.events.inputs.description}}"'
          fi
          if [[ $path_len -ge 1 ]]
          then
            parent='--parent "${{github.events.inputs.path}}"'
          fi
          echo "::set-output name=toc_hide::$toc_hide"
          echo "::set-output name=nav_hide::$nav_hide"
          echo "::set-output name=description::$description"
          echo "::set-output name=parent::$parent"
      - name: dry-run
        run: |
          echo "🐍 Creating category [dry-run]"
          python3 category.py "${{ inputs.category_name }}" --dry-run ${{ steps.args.outputs.toc_hide }} ${{ steps.args.outputs.nav_hide }} ${{ steps.args.outputs.description }} ${{ steps.args.outputs.parent }}
      - name: Set github accounts
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'






