name: Building Mkdocs Page

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - id: python_cache
        uses: actions/cache@v3
        with:
          path: venv
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
      - if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          # Check if venv exists (restored from secondary keys if any, and delete)
          # You might not need this line if you only have one primary key for the venv caching
          # I kept it in my code as a fail-safe
          if [ -d "venv" ]; then rm -rf venv; fi
          # Re-create the venv
          python3 -m venv venv
          # Install dependencies
          venv/bin/python3 -m pip install -r requirements.txt
      - run: |
          source venv/bin/activate
          mkdocs gh-deploy
