name: Building Mkdocs Page

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
concurrency:
  group: "pages"
  cancel-in-progress: true
  
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - id: python_cache
        name: Check python cache
        uses: actions/cache@v3
        with:
          path: venv
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
      - name: Install requirements
        if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          if [ -d "venv" ]; then rm -rf venv; fi
          python3 -m venv venv
          venv/bin/python3 -m pip install -r requirements.txt
      - name: Build Mkdocs
        id: pages
        uses: actions/configure-pages@v2
      - run: |
          source venv/bin/activate
          mkdocs build
      - name: Archive artifact 
        run: |
          chmod -c -R +rX "$INPUT_PATH" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cavf $RUNNER_TEMP/artifact.tar.bz2"
            --exclude=.git \
            --exclude=.github \
            .
        env:
          INPUT_PATH: ./site
      - name: Upload artifact
        uses: ctions/upload-artifact@main
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar.bz2
          retention-days: 1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: mkdocs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
