name: Publisher Manual
on: 
  workflow_dispatch:
    inputs:
      file:
        type: string
        description: File to convert by OBS2MK, glob pattern are supported (needed to convert a folder contents!)
        required: true

jobs:
  get_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: locate file
        run: |
          echo "${{ inputs.file }}"
          for i in $(find . -path "${{ inputs.file }}"); do
            echo "$i"
          done






