name: mkdocs_build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[PUBLISHER]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: set locale
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y
          sudo locale-gen fr
          lang="fr_FR.utf8"
          sudo update-locale LANG=$lang
      - run: mkdocs gh-deploy --force --clean
