name: mkdocs_build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[PUBLISHER]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.2
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with: 
          path: requirements.txt
      - name: get local
        id: yaml-data
        uses: KJ002/read-yaml@main
        with: 
          file: ./mkdocs.yml
          key-path: '["theme", "language"]'
      - name: set locale
        run: |
          echo "${{ steps.yaml-data.outputs.data }}"
          language=${{ steps.yaml-data.outputs.data }}
          sudo apt-get update && sudo apt-get install tzdata locales -y
          sudo locale-gen $language
          upperL="${language^^}"
          setLocale="$language"_"$upperL".utf8
          sudo update-locale LANG=$setLocale
      - run: mkdocs gh-deploy --force --clean
