name: mkdocs_build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[PUBLISHER]') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: mkdocs serve
        run: |
          mkdocs gh-deploy --force --clean
        
