name: mkdocs_build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[PUBLISHER]') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: set locale
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y
          lang=$(head -n 1 .github/.env)
          upperL="${lang^^}"
          newLang="$lang"_"$upperL".utf8
          sudo locale-gen $newLang
          locale -a | grep $lang
          sudo update-locale LANG=$newLang
          sudo update-locale LC_ALL=$newLang
          export LC_ALL=$newLang
          date
      - run: mkdocs gh-deploy --force --clean
