name: Sync Files
on: 
  push:
    paths:
      - overrides/**
      - .github/**

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Sync files
        uses: Redocly/repo-file-sync-action@master
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          SKIP_PR: true
