name: test changed
on: 
    push:
        branches: ['main', 'master']

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
      length-files: ${{ steps.lg_out.outputs.lg_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get changed files
        uses: tj-actions/changed-files@v23
        id: changed-files
        with:
          separator: ";"
          quotepath: "false"
          since_last_remote_commit: "true"
      - name: set lg outputs
        id: lg_out
        run: |
          changed=${{ steps.changed-files.outputs.all_changed_files }}
          lg_steps=${#changed}
          echo "$changed"
          echo "$lg_steps"
          echo "::set-output name=lg_files::$lg_steps"
          echo "::set-output name=changed-files::$changed"